branch: develop

search: False

schedule: "every month"

requirements:
  - tests/requirements-libraries.txt
  - tests/requirements-tools.txt:
      update: False

pr_prefix: "Tests: Requirements:"
label_prs: "area:tests/ci/pyup"

branch_prefix: pyup/
